DROP TABLE IF EXISTS tasks_3035705646;

CREATE TABLE tasks_3035705646 (
    task_id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE,
    title TEXT NOT NULL,
    is_completed BOOLEAN NOT NULL DEFAULT FALSE
);